#!/usr/bin/env bash
# Regenerate web/codemirror.bundle.js — the vendored CodeMirror 5 editor for the playground, as a
# single self-contained file. CodeMirror ships as many small files (core + addons + keymap + language
# modes + CSS); the Pages deploy (pages.yml "assemble site") copies only web/*.js and web/*.html, so a
# tree of files under a subdirectory would 404 in production. This concatenates the pinned upstream
# files in load order and appends a small injector for CodeMirror's own CSS, so one top-level *.js file
# carries the whole editor.
#
# CodeMirror is MIT-licensed, Copyright (C) 2017 by Marijn Haverbeke and others.
# Run from browser/:  ./build-codemirror-bundle.sh
set -euo pipefail

VERSION=5.65.16
BASE="https://cdn.jsdelivr.net/npm/codemirror@${VERSION}"
OUT=web/codemirror.bundle.js
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# JS files, in load order: core first, then the simple-mode + edit addons, the dialog/search addons Vim
# depends on, the Vim keymap, and the language modes.
JS=(
  lib/codemirror.js
  addon/mode/simple.js
  addon/edit/matchbrackets.js
  addon/dialog/dialog.js
  addon/search/searchcursor.js
  keymap/vim.js
  mode/lua/lua.js
  mode/sql/sql.js
  mode/clike/clike.js
  mode/javascript/javascript.js
)
CSS=(lib/codemirror.css addon/dialog/dialog.css)

for f in "${JS[@]}" "${CSS[@]}"; do
  mkdir -p "$TMP/$(dirname "$f")"
  curl -fsSL "$BASE/$f" -o "$TMP/$f"
done

{
  echo "// CodeMirror ${VERSION} — vendored bundle for the SVM playground editor (UI only; never"
  echo "// touches the sandbox or any authority). Generated by build-codemirror-bundle.sh from the"
  echo "// pinned upstream files at ${BASE}/. A single top-level file so the Pages assemble step"
  echo "// (which copies only web/*.js) deploys it; it also injects CodeMirror's own CSS. CodeMirror"
  echo "// is released under the MIT License, Copyright (C) 2017 by Marijn Haverbeke and others."
  echo "//"
  for f in "${JS[@]}"; do
    printf '\n// ==== %s ====\n\n' "$f"
    cat "$TMP/$f"
  done
} > "$OUT"

OUT="$OUT" node -e '
const fs = require("fs");
const css = process.argv.slice(1).map((p) => fs.readFileSync(p, "utf8")).join("\n");
const inj = "\n\n// ==== injected CSS (lib/codemirror.css + addon/dialog/dialog.css) ====\n"
  + ";(function(){var s=document.createElement(\"style\");s.textContent="
  + JSON.stringify(css) + ";document.head.insertBefore(s, document.head.firstChild);})();\n";
fs.appendFileSync(process.env.OUT, inj);
' "$TMP/lib/codemirror.css" "$TMP/addon/dialog/dialog.css"

node --check "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
