/* SQLite Phase A at corpus scale — a compact **sqllogictest runner** as a guest program.
 *
 * Reads a sqllogictest script (https://sqlite.org/sqllogictest/ — SQLite's own SQL Logic Tests,
 * the ≈600:1 validation corpus) from **stdin**, runs every record against an in-memory SQLite
 * (the same deterministic `SQLITE_OS_OTHER` build as `sqlite_demo.c`), and checks each query's
 * results against the expected values baked into the script — including the `N values hashing to
 * <md5>` form, via the embedded RFC-1321 MD5 below. Prints one `FAIL` line per mismatch and a
 * final summary, so the run is **self-validating** (failures must be 0: SQLite's own expected
 * results hold in the sandbox) *and* a clean **differential** (native build over the same stdin
 * must produce byte-identical output).
 *
 * Format notes (matching the reference `sqllogictest.c` runner byte-for-byte, since the corpus
 * hashes were generated by it):
 *   - value formatting: NULL → "NULL"; 'I' → "%d" of sqlite3_column_int (32-bit, as the reference
 *     does); 'R' → "%.3f"; 'T' → column text with "" → "(empty)" and chars outside 0x20..0x7e → '@';
 *   - `rowsort` orders whole rows, `valuesort` the flattened values, both before hashing;
 *   - the MD5 input is each value followed by "\n";
 *   - `skipif sqlite` / `onlyif <other-db>` records are skipped, `halt` stops the run.
 */

#define SQLITE_THREADSAFE 0
#define SQLITE_OMIT_LOAD_EXTENSION 1
#define SQLITE_OMIT_DEPRECATED 1
#define SQLITE_OMIT_WAL 1
#define SQLITE_OMIT_LOCALTIME 1
#define SQLITE_TEMP_STORE 3
#define SQLITE_OS_OTHER 1
#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_MAX_MMAP_SIZE 0
#define SQLITE_DQS 0
#define NDEBUG 1

#include "sqlite3.c"

/* ---- deterministic minimal VFS (same as sqlite_demo.c) --------------------------------------- */

static int demoRandomness(sqlite3_vfs *unused, int n, char *out) {
  static unsigned long long s = 0x9E3779B97F4A7C15ull;
  (void)unused;
  for (int i = 0; i < n; i++) {
    s += 0x9E3779B97F4A7C15ull;
    unsigned long long z = s;
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
    out[i] = (char)(z >> 33);
  }
  return n;
}
static int demoSleep(sqlite3_vfs *u, int us) {
  (void)u;
  return us;
}
static int demoCurrentTime(sqlite3_vfs *u, double *t) {
  (void)u;
  *t = 2460310.5;
  return SQLITE_OK;
}
static int demoCurrentTimeInt64(sqlite3_vfs *u, sqlite3_int64 *t) {
  (void)u;
  *t = 212570827200000LL;
  return SQLITE_OK;
}
static int demoOpen(sqlite3_vfs *u, const char *n, sqlite3_file *f, int fl, int *o) {
  (void)u;
  (void)n;
  (void)f;
  (void)fl;
  (void)o;
  return SQLITE_CANTOPEN;
}
static int demoDelete(sqlite3_vfs *u, const char *n, int s) {
  (void)u;
  (void)n;
  (void)s;
  return SQLITE_OK;
}
static int demoAccess(sqlite3_vfs *u, const char *n, int f, int *o) {
  (void)u;
  (void)n;
  (void)f;
  *o = 0;
  return SQLITE_OK;
}
static int demoFullPathname(sqlite3_vfs *u, const char *n, int len, char *o) {
  (void)u;
  int i = 0;
  for (; n[i] && i < len - 1; i++) o[i] = n[i];
  o[i] = 0;
  return SQLITE_OK;
}
static int demoGetLastError(sqlite3_vfs *u, int n, char *o) {
  (void)u;
  (void)n;
  (void)o;
  return 0;
}

SQLITE_API int sqlite3_os_init(void) {
  static sqlite3_vfs demoVfs = {
      2,  sizeof(sqlite3_file), 512, 0, "svm-demo", 0,
      demoOpen, demoDelete, demoAccess, demoFullPathname,
      0, 0, 0, 0,
      demoRandomness, demoSleep, demoCurrentTime, demoGetLastError, demoCurrentTimeInt64,
      0, 0, 0,
  };
  return sqlite3_vfs_register(&demoVfs, 1);
}
SQLITE_API int sqlite3_os_end(void) { return SQLITE_OK; }

/* ---- RFC 1321 MD5 (public-domain style, compact) --------------------------------------------- */

typedef struct {
  unsigned int h[4];
  unsigned long long len;
  unsigned char buf[64];
  int n;
} Md5;

static unsigned int md5_rol(unsigned int x, int c) { return (x << c) | (x >> (32 - c)); }

static void md5_block(Md5 *m, const unsigned char *p) {
  static const unsigned int K[64] = {
      0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee, 0xf57c0faf, 0x4787c62a, 0xa8304613,
      0xfd469501, 0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be, 0x6b901122, 0xfd987193,
      0xa679438e, 0x49b40821, 0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa, 0xd62f105d,
      0x02441453, 0xd8a1e681, 0xe7d3fbc8, 0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
      0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a, 0xfffa3942, 0x8771f681, 0x6d9d6122,
      0xfde5380c, 0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70, 0x289b7ec6, 0xeaa127fa,
      0xd4ef3085, 0x04881d05, 0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665, 0xf4292244,
      0x432aff97, 0xab9423a7, 0xfc93a039, 0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
      0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1, 0xf7537e82, 0xbd3af235, 0x2ad7d2bb,
      0xeb86d391};
  static const int R[64] = {7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22,
                            5, 9,  14, 20, 5, 9,  14, 20, 5, 9,  14, 20, 5, 9,  14, 20,
                            4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23,
                            6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21};
  unsigned int w[16];
  for (int i = 0; i < 16; i++) {
    w[i] = (unsigned int)p[i * 4] | ((unsigned int)p[i * 4 + 1] << 8) |
           ((unsigned int)p[i * 4 + 2] << 16) | ((unsigned int)p[i * 4 + 3] << 24);
  }
  unsigned int a = m->h[0], b = m->h[1], c = m->h[2], d = m->h[3];
  for (int i = 0; i < 64; i++) {
    unsigned int f;
    int g;
    if (i < 16) {
      f = (b & c) | (~b & d);
      g = i;
    } else if (i < 32) {
      f = (d & b) | (~d & c);
      g = (5 * i + 1) & 15;
    } else if (i < 48) {
      f = b ^ c ^ d;
      g = (3 * i + 5) & 15;
    } else {
      f = c ^ (b | ~d);
      g = (7 * i) & 15;
    }
    unsigned int tmp = d;
    d = c;
    c = b;
    b = b + md5_rol(a + f + K[i] + w[g], R[i]);
    a = tmp;
  }
  m->h[0] += a;
  m->h[1] += b;
  m->h[2] += c;
  m->h[3] += d;
}

static void md5_init(Md5 *m) {
  m->h[0] = 0x67452301;
  m->h[1] = 0xefcdab89;
  m->h[2] = 0x98badcfe;
  m->h[3] = 0x10325476;
  m->len = 0;
  m->n = 0;
}

static void md5_update(Md5 *m, const char *data, long n) {
  m->len += (unsigned long long)n;
  for (long i = 0; i < n; i++) {
    m->buf[m->n++] = (unsigned char)data[i];
    if (m->n == 64) {
      md5_block(m, m->buf);
      m->n = 0;
    }
  }
}

static void md5_hex(Md5 *m, char out[33]) {
  unsigned long long bits = m->len * 8;
  unsigned char pad = 0x80;
  md5_update(m, (const char *)&pad, 1);
  unsigned char z = 0;
  while (m->n != 56) md5_update(m, (const char *)&z, 1);
  unsigned char lenb[8];
  for (int i = 0; i < 8; i++) lenb[i] = (unsigned char)(bits >> (8 * i));
  md5_update(m, (const char *)lenb, 8);
  static const char hexd[] = "0123456789abcdef";
  for (int i = 0; i < 16; i++) {
    unsigned char byte = (unsigned char)(m->h[i / 4] >> (8 * (i & 3)));
    out[i * 2] = hexd[byte >> 4];
    out[i * 2 + 1] = hexd[byte & 15];
  }
  out[32] = 0;
}

/* ---- tiny libc-ish helpers ------------------------------------------------------------------- */

extern long read(int fd, void *buf, long n);

static long slen(const char *s) {
  long n = 0;
  while (s[n]) n++;
  return n;
}
static int seq(const char *a, const char *b) {
  long i = 0;
  for (; a[i] && b[i]; i++)
    if (a[i] != b[i]) return 0;
  return a[i] == b[i];
}
static int sprefix(const char *s, const char *p) {
  long i = 0;
  for (; p[i]; i++)
    if (s[i] != p[i]) return 0;
  return 1;
}
static int scmp(const char *a, const char *b) {
  long i = 0;
  for (; a[i] && a[i] == b[i]; i++) {}
  return (unsigned char)a[i] < (unsigned char)b[i] ? -1 : (a[i] == b[i] ? 0 : 1);
}

/* Read all of stdin into a growable NUL-terminated buffer. */
static char *read_stdin(long *out_len) {
  long cap = 1 << 16, len = 0;
  char *buf = sqlite3_malloc64((sqlite3_uint64)cap);
  for (;;) {
    if (len + 4096 > cap) {
      cap *= 2;
      buf = sqlite3_realloc64(buf, (sqlite3_uint64)cap);
    }
    long n = read(0, buf + len, 4096);
    if (n <= 0) break;
    len += n;
  }
  buf[len] = 0;
  *out_len = len;
  return buf;
}

/* ---- the runner ------------------------------------------------------------------------------ */

static sqlite3 *g_db;
static int n_ok, n_fail, n_skip, n_records;

/* One formatted result value (malloc'd). */
static char **g_vals;
static long g_nvals, g_vcap;

static void push_val(char *v) {
  if (g_nvals == g_vcap) {
    g_vcap = g_vcap ? g_vcap * 2 : 64;
    g_vals = sqlite3_realloc64(g_vals, (sqlite3_uint64)(g_vcap * sizeof(char *)));
  }
  g_vals[g_nvals++] = v;
}

/* Format one column exactly as the reference runner does. */
static char *format_col(sqlite3_stmt *st, int i, char type) {
  char tmp[40];
  if (sqlite3_column_type(st, i) == SQLITE_NULL) {
    char *v = sqlite3_malloc64(5);
    v[0] = 'N'; v[1] = 'U'; v[2] = 'L'; v[3] = 'L'; v[4] = 0;
    return v;
  }
  if (type == 'I') {
    sqlite3_snprintf(sizeof tmp, tmp, "%d", sqlite3_column_int(st, i));
  } else if (type == 'R') {
    sqlite3_snprintf(sizeof tmp, tmp, "%.3f", sqlite3_column_double(st, i));
  } else {
    const unsigned char *z = sqlite3_column_text(st, i);
    long n = slen((const char *)z);
    if (n == 0) {
      char *v = sqlite3_malloc64(8);
      const char *e = "(empty)";
      for (int k = 0; k < 8; k++) v[k] = e[k];
      return v;
    }
    char *v = sqlite3_malloc64((sqlite3_uint64)n + 1);
    for (long k = 0; k < n; k++) {
      v[k] = (z[k] < 0x20 || z[k] > 0x7e) ? '@' : (char)z[k];
    }
    v[n] = 0;
    return v;
  }
  long n = slen(tmp);
  char *v = sqlite3_malloc64((sqlite3_uint64)n + 1);
  for (long k = 0; k <= n; k++) v[k] = tmp[k];
  return v;
}

/* Merge sort over an index permutation — `width` values per row, rows compared column-major. */
static long *g_perm, *g_scratch;
static int row_lt(long ra, long rb, long width) {
  for (long c = 0; c < width; c++) {
    int d = scmp(g_vals[ra * width + c], g_vals[rb * width + c]);
    if (d) return d < 0;
  }
  return 0;
}
static void msort(long lo, long hi, long width) {
  if (hi - lo < 2) return;
  long mid = lo + (hi - lo) / 2;
  msort(lo, mid, width);
  msort(mid, hi, width);
  long i = lo, j = mid, k = lo;
  while (i < mid && j < hi) g_scratch[k++] = row_lt(g_perm[j], g_perm[i], width) ? g_perm[j++] : g_perm[i++];
  while (i < mid) g_scratch[k++] = g_perm[i++];
  while (j < hi) g_scratch[k++] = g_perm[j++];
  for (k = lo; k < hi; k++) g_perm[k] = g_scratch[k];
}

int main(void) {
  long src_len;
  char *src = read_stdin(&src_len);
  if (sqlite3_open(":memory:", &g_db) != SQLITE_OK) {
    printf("cannot open :memory:\n");
    return 1;
  }

  /* Line cursor over `src` (NUL-terminate each line in place). */
  long pos = 0;
  long lineno = 0;
  char sql[65536];

  while (pos < src_len) {
    /* --- read one record's header, skipping blank/comment lines --- */
    int skip = 0;
    char *line;
    long rec_line;
    for (;;) {
      if (pos >= src_len) goto done;
      line = src + pos;
      long e = pos;
      while (src[e] && src[e] != '\n') e++;
      long next = src[e] ? e + 1 : e;
      src[e] = 0;
      if (e > pos && src[e - 1] == '\r') src[e - 1] = 0; /* CRLF-tolerant */
      pos = next;
      lineno++;
      if (line[0] == 0 || line[0] == '#') continue;
      if (sprefix(line, "skipif ")) {
        if (seq(line + 7, "sqlite")) skip = 1;
        continue;
      }
      if (sprefix(line, "onlyif ")) {
        if (!seq(line + 7, "sqlite")) skip = 1;
        continue;
      }
      if (sprefix(line, "hash-threshold")) { /* informational — we follow the file's own format */
        continue;
      }
      if (seq(line, "halt")) goto done;
      break; /* `statement …` or `query …` */
    }
    rec_line = lineno;
    n_records++;

    /* --- collect the SQL (lines up to blank, or `----` for a query) --- */
    int is_query = sprefix(line, "query ");
    int is_statement = sprefix(line, "statement ");
    char header[128];
    {
      long n = slen(line);
      if (n > 127) n = 127;
      for (long k = 0; k <= n; k++) header[k] = line[k];
      header[127] = 0;
    }
    long sql_len = 0;
    int saw_separator = 0;
    for (;;) {
      if (pos >= src_len) break;
      char *l = src + pos;
      long e = pos;
      while (src[e] && src[e] != '\n') e++;
      long next = src[e] ? e + 1 : e;
      src[e] = 0;
      if (e > pos && src[e - 1] == '\r') src[e - 1] = 0; /* CRLF-tolerant */
      pos = next;
      lineno++;
      if (l[0] == 0) break;
      if (is_query && seq(l, "----")) {
        saw_separator = 1;
        break;
      }
      long n = slen(l);
      if (sql_len + n + 2 < (long)sizeof sql) {
        if (sql_len) sql[sql_len++] = '\n';
        for (long k = 0; k < n; k++) sql[sql_len + k] = l[k];
        sql_len += n;
      }
    }
    sql[sql_len] = 0;

    /* --- expected results (queries only) --- */
    char *expected[4096];
    long n_expected = 0;
    long hash_count = -1;
    char hash_hex[64];
    if (is_query && saw_separator) {
      for (;;) {
        if (pos >= src_len) break;
        char *l = src + pos;
        long e = pos;
        while (src[e] && src[e] != '\n') e++;
        long next = src[e] ? e + 1 : e;
        src[e] = 0;
        if (e > pos && src[e - 1] == '\r') src[e - 1] = 0; /* CRLF-tolerant */
        pos = next;
        lineno++;
        if (l[0] == 0) break;
        /* "N values hashing to <hex>" */
        if (n_expected == 0 && hash_count < 0) {
          long v = 0, i = 0;
          while (l[i] >= '0' && l[i] <= '9') v = v * 10 + (l[i++] - '0');
          if (i > 0 && sprefix(l + i, " values hashing to ")) {
            hash_count = v;
            long j = i + 19, k = 0;
            while (l[j] && k < 63) hash_hex[k++] = l[j++];
            hash_hex[k] = 0;
            continue;
          }
        }
        if (n_expected < 4096) expected[n_expected++] = l;
      }
    }

    if (skip) {
      n_skip++;
      continue;
    }

    /* --- execute --- */
    if (is_statement) {
      int want_ok = sprefix(header, "statement ok");
      char *err = 0;
      int rc = sqlite3_exec(g_db, sql, 0, 0, &err);
      int ok = want_ok ? rc == SQLITE_OK : rc != SQLITE_OK;
      if (!ok) {
        printf("FAIL line %d: statement %s (rc=%d %s)\n", (int)rec_line,
               want_ok ? "failed" : "unexpectedly succeeded", rc, err ? err : "");
        n_fail++;
      } else {
        n_ok++;
      }
      sqlite3_free(err);
      continue;
    }
    if (!is_query) {
      printf("FAIL line %d: unrecognized record `%s`\n", (int)rec_line, header);
      n_fail++;
      continue;
    }

    /* header: query <types> [sortmode] [label] */
    const char *types = header + 6;
    char sortmode = 'n'; /* n=nosort r=rowsort v=valuesort */
    {
      const char *sp = types;
      while (*sp && *sp != ' ') sp++;
      if (*sp) {
        const char *m = sp + 1;
        if (sprefix(m, "rowsort")) sortmode = 'r';
        else if (sprefix(m, "valuesort")) sortmode = 'v';
      }
    }
    long width = 0;
    while (types[width] && types[width] != ' ') width++;

    sqlite3_stmt *st = 0;
    int rc = sqlite3_prepare_v2(g_db, sql, -1, &st, 0);
    if (rc != SQLITE_OK) {
      printf("FAIL line %d: query prepare rc=%d: %s\n", (int)rec_line, rc, sqlite3_errmsg(g_db));
      sqlite3_finalize(st);
      n_fail++;
      continue;
    }
    g_nvals = 0;
    while ((rc = sqlite3_step(st)) == SQLITE_ROW) {
      for (long i = 0; i < width; i++) push_val(format_col(st, (int)i, types[i]));
    }
    sqlite3_finalize(st);
    if (rc != SQLITE_DONE) {
      printf("FAIL line %d: query step rc=%d: %s\n", (int)rec_line, rc, sqlite3_errmsg(g_db));
      for (long i = 0; i < g_nvals; i++) sqlite3_free(g_vals[i]);
      n_fail++;
      continue;
    }

    /* sort */
    long nrows = width ? g_nvals / width : 0;
    long sort_n = sortmode == 'r' ? nrows : g_nvals;
    long sort_w = sortmode == 'r' ? width : 1;
    g_perm = sqlite3_malloc64((sqlite3_uint64)((g_nvals ? g_nvals : 1) * sizeof(long)));
    g_scratch = sqlite3_malloc64((sqlite3_uint64)((g_nvals ? g_nvals : 1) * sizeof(long)));
    for (long i = 0; i < (sort_n ? sort_n : 0); i++) g_perm[i] = i;
    if (sortmode != 'n') msort(0, sort_n, sort_w);

    /* materialize the check order: perm over rows (r) / values (v) / identity (n) */
    int failed = 0;
    if (hash_count >= 0) {
      Md5 m;
      md5_init(&m);
      for (long i = 0; i < sort_n; i++) {
        long base = (sortmode == 'n' ? i : g_perm[i]) * sort_w;
        for (long c = 0; c < sort_w; c++) {
          md5_update(&m, g_vals[base + c], slen(g_vals[base + c]));
          md5_update(&m, "\n", 1);
        }
      }
      char hex[33];
      md5_hex(&m, hex);
      if (g_nvals != hash_count || !seq(hex, hash_hex)) {
        printf("FAIL line %d: hash mismatch (%d values, got %s want %s)\n", (int)rec_line,
               (int)g_nvals, hex, hash_hex);
        failed = 1;
      }
    } else {
      if (g_nvals != n_expected) {
        printf("FAIL line %d: %d values, expected %d\n", (int)rec_line, (int)g_nvals,
               (int)n_expected);
        failed = 1;
      } else {
        long idx = 0;
        for (long i = 0; i < sort_n && !failed; i++) {
          long base = (sortmode == 'n' ? i : g_perm[i]) * sort_w;
          for (long c = 0; c < sort_w && !failed; c++, idx++) {
            if (!seq(g_vals[base + c], expected[idx])) {
              printf("FAIL line %d: value %d is `%s`, expected `%s`\n", (int)rec_line, (int)idx,
                     g_vals[base + c], expected[idx]);
              failed = 1;
            }
          }
        }
      }
    }
    sqlite3_free(g_perm);
    sqlite3_free(g_scratch);
    for (long i = 0; i < g_nvals; i++) sqlite3_free(g_vals[i]);
    if (failed) n_fail++;
    else n_ok++;
  }

done:
  printf("records=%d ok=%d failed=%d skipped=%d\n", n_records, n_ok, n_fail, n_skip);
  sqlite3_close(g_db);
  return n_fail > 0 ? 1 : 0;
}
